## Testing Mistral performance on 120 samples

Setup, load prompt, data

In [4]:
# If needed:
# %pip install mistralai pandas openpyxl scikit-learn simpledorff

import os
import json
import time
import pandas as pd
import numpy as np

from dotenv import load_dotenv
from mistralai.client import Mistral

load_dotenv()

client = Mistral(
    api_key=os.environ["MISTRAL_API_KEY"]
)

import importlib
import frame_prompts

importlib.reload(frame_prompts)

# --------------------------------------------------
# CHOOSE PROMPT
# --------------------------------------------------

SYSTEM_PROMPT = frame_prompts.OPERATIONALIZED_JOINT_PROMPT

PROMPT_NAME = "operationalized_joint"


# --------------------------------------------------
# MISTRAL SETTINGS
# --------------------------------------------------

MODEL = "mistral-large-latest"

client = Mistral(
    api_key=os.environ["MISTRAL_API_KEY"]
)


# --------------------------------------------------
# LOAD GOLD DATA
# --------------------------------------------------

df = pd.read_excel("frame_gold.xlsx")

required_columns = [
    "uuid",
    "title",
    "protest_excerpt",
    "title_frame",
    "excerpt_frame",
    "demands_present",
    "protester_quote",
    "authority_quote",
    "thematic_present",
]

missing = [c for c in required_columns if c not in df.columns]

if missing:
    raise ValueError(f"Missing columns: {missing}")

df = df[required_columns].copy()

df["title"] = df["title"].fillna("").astype(str)
df["protest_excerpt"] = df["protest_excerpt"].fillna("").astype(str)


# --------------------------------------------------
# NORMALIZE GOLD LABELS
# --------------------------------------------------

label_columns = [
    "title_frame",
    "excerpt_frame",
    "demands_present",
    "protester_quote",
    "authority_quote",
    "thematic_present",
]

for col in label_columns:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
        .str.replace(" ", "_", regex=False)
    )

df["title_frame"] = df["title_frame"].replace(
    "violence",
    "protester_violence"
)

df["excerpt_frame"] = df["excerpt_frame"].replace(
    "violence",
    "protester_violence"
)


# --------------------------------------------------
# TEST FIRST
# --------------------------------------------------

test_df = df.head(3).copy()

RUN_DF = df

# When ready:
# RUN_DF = df

print(f"Running {len(RUN_DF)} samples.")
print(f"Model: {MODEL}")
print(f"Prompt: {PROMPT_NAME}")

Running 120 samples.
Model: mistral-large-latest
Prompt: operationalized_joint

schema + API call + run

In [6]:
# ============================================================
# VALID LABELS
# ============================================================

FRAME_LABELS = [
    "protester_violence",
    "harm_to_protesters",
    "property_damage",
    "disruption",
    "grievance",
    "widespread_support",
    "peaceful",
    "impactful",
    "residual",
]

BINARY_LABELS = ["yes", "no"]


# ============================================================
# FORMAT INPUT
# ============================================================

def format_input(title, excerpt):
    return f"""TITLE:
{title}

EXCERPT:
{excerpt}
"""


# ============================================================
# VALIDATE MODEL OUTPUT
# ============================================================

def validate_annotation(annotation):

    required_keys = {
        "title_frame",
        "excerpt_frame",
        "demands_present",
        "protester_quote",
        "authority_quote",
        "thematic_present",
    }

    if set(annotation.keys()) != required_keys:
        raise ValueError(
            f"Unexpected JSON keys: {annotation.keys()}"
        )

    if annotation["title_frame"] not in FRAME_LABELS:
        raise ValueError(
            f"Invalid title_frame: {annotation['title_frame']}"
        )

    if annotation["excerpt_frame"] not in FRAME_LABELS:
        raise ValueError(
            f"Invalid excerpt_frame: {annotation['excerpt_frame']}"
        )

    for col in [
        "demands_present",
        "protester_quote",
        "authority_quote",
        "thematic_present",
    ]:
        if annotation[col] not in BINARY_LABELS:
            raise ValueError(
                f"Invalid {col}: {annotation[col]}"
            )

    return annotation


# ============================================================
# CALL MISTRAL
# ============================================================

def annotate_sample(title, excerpt, max_retries=3):

    messages = [
        {
            "role": "system",
            "content": SYSTEM_PROMPT,
        },
        {
            "role": "user",
            "content": format_input(title, excerpt),
        },
    ]

    for attempt in range(max_retries):

        try:

            response = client.chat.complete(
                model=MODEL,
                messages=messages,

                # JSON mode ensures valid JSON.
                response_format={
                    "type": "json_object"
                },

                temperature=0,
            )

            raw_text = response.choices[0].message.content

            annotation = json.loads(raw_text)

            annotation = validate_annotation(annotation)

            # Usage fields may vary slightly by SDK version,
            # so access them defensively.
            input_tokens = getattr(
                response.usage,
                "prompt_tokens",
                None
            )

            output_tokens = getattr(
                response.usage,
                "completion_tokens",
                None
            )

            return {
                **annotation,
                "input_tokens": input_tokens,
                "output_tokens": output_tokens,
                "raw_response": raw_text,
                "error": None,
            }

        except Exception as e:

            print(
                f"Attempt {attempt + 1}/{max_retries} failed: "
                f"{type(e).__name__}: {e}"
            )

            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)

            else:

                return {
                    "title_frame": None,
                    "excerpt_frame": None,
                    "demands_present": None,
                    "protester_quote": None,
                    "authority_quote": None,
                    "thematic_present": None,
                    "input_tokens": None,
                    "output_tokens": None,
                    "raw_response": None,
                    "error": str(e),
                }


# ============================================================
# RUN
# ============================================================

results = []

for count, (_, row) in enumerate(
    RUN_DF.iterrows(),
    start=1
):

    print(
        f"[{count}/{len(RUN_DF)}] "
        f"{row['uuid']}"
    )

    prediction = annotate_sample(
        title=row["title"],
        excerpt=row["protest_excerpt"],
    )

    prediction["uuid"] = row["uuid"]

    results.append(prediction)
    time.sleep(15)


pred_df = pd.DataFrame(results)


# ============================================================
# RENAME PREDICTIONS
# ============================================================

pred_df = pred_df.rename(columns={
    "title_frame": "pred_title_frame",
    "excerpt_frame": "pred_excerpt_frame",
    "demands_present": "pred_demands_present",
    "protester_quote": "pred_protester_quote",
    "authority_quote": "pred_authority_quote",
    "thematic_present": "pred_thematic_present",
})


# ============================================================
# MERGE BY UUID
# ============================================================

results_df = RUN_DF.merge(
    pred_df,
    on="uuid",
    how="left",
    validate="one_to_one"
)


# ============================================================
# SAVE IMMEDIATELY
# ============================================================

output_file = (
    f"{PROMPT_NAME}_{MODEL}.xlsx"
)

results_df.to_excel(
    output_file,
    index=False
)

print(f"\nSaved: {output_file}")

print(
    f"Successful: "
    f"{results_df['error'].isna().sum()}"
)

print(
    f"Errors: "
    f"{results_df['error'].notna().sum()}"
)

if results_df["input_tokens"].notna().any():
    print(
        f"Average input tokens: "
        f"{results_df['input_tokens'].mean():,.0f}"
    )

if results_df["output_tokens"].notna().any():
    print(
        f"Average output tokens: "
        f"{results_df['output_tokens'].mean():,.0f}"
    )

display(results_df.head())

[1/120] d1334539-4cf3-4c5f-a0ef-88db5f167395
[2/120] b088e93f-1de4-4021-97bf-a90700b0a0ac
[3/120] fffb4a3a-8ee2-4cc4-9b9a-b0f676c5bdad
[4/120] 155faae5-c8b6-441e-a20e-dce06e01cf32
[5/120] 50fea669-6828-44de-8a70-b448e398be11
[6/120] 81efb265-e3ba-4508-adc7-73cbc029f359
[7/120] 5fb219a8-9df7-4ad0-bc57-d46be3e327e0
[8/120] 252fb33d-5e6c-4cff-acc0-98c253f6c4b8
[9/120] 4acf5304-e74d-4a4f-bee0-caf65bd02abe
[10/120] 74fd09e2-35a3-495b-9b59-1610ec3398e1
[11/120] 7d9d161f-8087-4e0b-89e2-4a9bc1dcfd9d
[12/120] 0c5fa89f-f32f-4014-98e5-e8ad481b8a2f
[13/120] b2a2ef91-319a-47bf-9a61-1f8b4e192abf
[14/120] a92ef5b3-9891-4492-8a32-5024d7cc52dc
[15/120] c13350d6-ae7e-43f9-8999-17e530a4c80b
[16/120] 874c16ec-4684-40c7-8928-06baaa20260d
[17/120] 0192cd22-a165-4eb8-bf6d-da6165164b2e
[18/120] 95c2c809-f17e-4d9d-af74-26ba987929cd
[19/120] 109cd735-179b-4d53-ba32-ac1b70d5d990
[20/120] 36ab3319-2965-4075-80bd-14627327ab65
[21/120] f4bf7615-7d65-4e3d-b332-fbf590087f99
[22/120] 58a57f20-02b7-4389-9add-4cd5c76aae79
[23/120] d951048b-96bf-4f1a-812d-d37093c86e90
[24/120] c388a480-bee6-4308-8844-c8bb0b12c7a0
[25/120] d0b49142-f2cf-465c-994e-f24d07477a56
[26/120] 9a7fcd80-a3ff-47fa-ab3e-b24058917228
[27/120] 402c9f4d-26ac-4215-91fa-231c982f8d26
[28/120] 5cc26d4f-b198-4dbb-a8a9-7ab848a1f997
[29/120] 49cd927b-3038-4744-975f-14d839032ac7
[30/120] b4005357-c83f-4004-9a38-ed5399c1a77c
[31/120] 42ca7d15-0263-4944-879d-c3e9351f70a8
[32/120] 34112ef7-f484-4411-899f-ffa7b0fc8ca5
[33/120] a6d3e4f9-a096-4c83-9b87-905af5e54301
[34/120] 91a3f3fa-9838-431b-8a85-851aca909486
[35/120] 938d5cf3-2900-43ff-a50f-6ac45e8f3aa4
[36/120] 6970867e-b4b2-4487-b134-da9903b374b6
[37/120] ce94e5cb-29d9-4f4c-b91e-117ff3a74474
[38/120] 50275382-1755-4359-bcfb-baccd1b2e65e
[39/120] 1c878f00-1989-464c-bc13-e00e0dba2e68
[40/120] 54e1ecb6-5daf-48b2-95fd-c31c6f954296
[41/120] 8cab1ac5-7998-4a92-9cfc-aaf7f1666fd7
[42/120] 846b56b7-3b93-4b5a-97de-0c69bd3860e6
[43/120] 993582b2-5dad-427a-8e51-68ddfebfdec9
[44/120] 76615b17-4930-4c12-a0a0-f302e2947a86
[45/120] a09f3465-a310-4716-882a-10a9ac5a6e16
[46/120] 2d6f8144-9af6-4010-a23c-c918d4ad27f2
[47/120] 0998a0c1-002f-4afe-92a4-6a0795357e34
[48/120] e7935ca8-3680-4ba0-9ab7-75bb28b13447
[49/120] d7b9a833-b5ff-4a04-9a7a-ab90adb97e1e
[50/120] 1cb7e6f6-944f-4d62-9257-263536835ef8
[51/120] 67f71419-adca-496c-b73a-dde4db7f3191
[52/120] cd802fcf-7f65-41d6-97a2-b102bea8a3ce
[53/120] 2da731fa-6040-4412-85a3-5ab7415ba5ff
[54/120] a9c3d331-868f-4e01-bbbc-e780eab198b5
[55/120] 7e5e0312-93dd-4108-b7a4-c31263b44cd8
[56/120] 41f460d7-0c9f-4b03-92e7-81f4ada49115
[57/120] 3001dd1e-4ea2-4e94-83ad-d9bbcc5275c8
[58/120] 3eb82a7a-4d8f-4274-9cb1-a515454c2cc9
[59/120] 932af827-8af2-4532-8de3-26c2ebff6e49
[60/120] 5e497a37-351c-453d-a28d-874467b56c3a
[61/120] 817746e9-192f-4f41-81fc-6576fb8b1d46
[62/120] 119d433c-3820-4d14-82b5-7af0b73d9d24
[63/120] 659e1a63-db75-4fa8-9973-4c06f29c1148
[64/120] 8dbb8b86-43f4-4513-a9f5-1a75a5c173a7
[65/120] df34b27f-dd95-4afe-9806-1511dbccbc26
[66/120] 9b835c1e-54a3-45fa-a7a9-19ac82502a30
[67/120] bfc7273a-9553-4e9b-874c-3fa9f8bbc57d
[68/120] 2c9f9302-f7bc-4615-804a-8f638260e441
[69/120] 96161ae2-cc8c-469a-b186-94b41e5c5177
[70/120] 5d39baa3-37ba-4f33-b411-1a68c7178064
[71/120] 1abd73de-03b9-4817-9dd7-52209da460dc
[72/120] 1de1f3c4-7829-4375-bafb-49cdee34a4e4
[73/120] cadc75c5-d3a1-4f82-9c46-463846328df9
[74/120] b408058b-c41a-4e04-bff3-4b8071c09fea
[75/120] a1b5bd0c-96e8-41a7-8e05-190314417cc1
[76/120] 322dc51e-5edb-46e3-8abe-43eb6d9d5e8b
[77/120] d59d5b65-771a-4964-a057-7a7d67ba84b8
[78/120] 00f55206-5eca-4c54-98ed-3c8b8c8b9797
[79/120] 9646b88d-3a40-4bef-8f10-3ba21a8df555
[80/120] 77e732d2-aeb3-4e0c-b5f4-e86f0f4b5fa5
[81/120] 346593b4-6bd6-476e-9b18-060e93214b10
[82/120] f8c603e9-bcb3-4d09-b01c-20e1a80457f0
[83/120] 0bda2100-bb28-4934-a24a-bc28ea037572
[84/120] 9d530c02-5040-4817-9942-10952ea53a02
[85/120] a4a3a245-fae7-4a17-a133-1ab4bd250922
[86/120] c76938cb-f257-4eec-936e-6d4f2a8b5a8f
[87/120] ae95496d-766d-4c3f-b909-b38a5ec019a6
[88/120] 1f29f0bf-f365-459d-a947-d48f0a58b289
[89/120] c15613b3-6a66-4705-8841-2e4437849450
[90/120] fee8698b-6c1a-4dfe-9b06-9b938f739b95
[91/120] 3522dc89-8b93-4d38-8660-a670262d1496
[92/120] e6dde810-bf10-400c-93d7-874381419c89
[93/120] d21b3569-1a59-4d23-a803-b75d797142e4
[94/120] f6590bf2-3180-4fc9-96c1-a5a6f21fdc9b
[95/120] 06c8d3f0-e8f6-4978-b4d0-38820d6f3c44
[96/120] 3270138d-8f3a-4484-90d7-0645c8890571
[97/120] 1a68f92f-abb3-41bb-87df-648c6fd07ccc
[98/120] c42f9186-88da-443e-a70d-abb356c86db2
[99/120] 2a6dbf0a-43b5-4628-b788-0ba0c4082671
[100/120] eebbe1df-5541-4f2d-aa85-55aa70dc0a68
[101/120] 189c2277-8c22-4230-823a-7317277413d4
[102/120] 7c00a71e-0a01-44e7-b14c-a879e118a228
[103/120] 99a7ca61-c4e3-4f73-935f-e9b239336c92
[104/120] 83c2698d-75ca-47d9-9d2f-1dd18c897dd2
[105/120] d81104e8-c58e-45ba-8efd-70d986c0469f
[106/120] 270688b1-d49e-40dd-92f6-a3ce0a59fb0c
[107/120] dc36ec29-e41f-4bf2-b731-3e8c67d965e7
[108/120] 3d642c59-b985-4012-9188-eb5b565d0c92
[109/120] 832062d2-1112-41f4-8409-64e22ed48541
[110/120] 30053e01-3374-4c80-982a-fa9e33b5e8c2
[111/120] 1b88181f-0825-4ac8-a8a5-5203f8ca2fe6
[112/120] e26eecb3-6e5f-456d-b05a-fc7008ed9de9
[113/120] ccd1e21d-6ed1-46bc-aa68-82d46f5eeefa
[114/120] 46afecef-5908-478f-81b2-26e9a7c48bce
[115/120] b914c148-a68e-4cbd-8110-44000a1938d8
[116/120] 559e0342-5214-4672-86dc-1c16db863422
[117/120] 94c2367b-5c21-4e9a-ae26-737c42c6a742
[118/120] 2ed7785a-1b12-4aa6-8210-6baf29d59351
[119/120] c2b639e1-236d-4f8f-9c03-bda271d30d18
[120/120] 0365b61a-13b7-477b-b73a-9ee070076a57

Saved: operationalized_joint_mistral-large-latest.xlsx
Successful: 120
Errors: 0
Average input tokens: 4,797
Average output tokens: 66

,uuid,title,protest_excerpt,title_frame,excerpt_frame,demands_present,protester_quote,authority_quote,thematic_present,pred_title_frame,pred_excerpt_frame,pred_demands_present,pred_protester_quote,pred_authority_quote,pred_thematic_present,input_tokens,output_tokens,raw_response,error
0,d1334539-4cf3-4c5f-a0ef-88db5f167395,Third politician in a month killed in Ecuador,The gang boss was moved out of a jail with lig...,residual,grievance,yes,no,no,no,residual,grievance,yes,yes,no,no,4528,64,"{\n ""title_frame"": ""residual"",\n ""excerpt_fr...",None
1,b088e93f-1de4-4021-97bf-a90700b0a0ac,Amazon CEO tells staff to work in office three...,This comes after Amazon said it would lay off ...,residual,widespread_support,yes,yes,no,yes,residual,grievance,yes,yes,no,no,4601,64,"{\n ""title_frame"": ""residual"",\n ""excerpt_fr...",None
2,fffb4a3a-8ee2-4cc4-9b9a-b0f676c5bdad,Gaza ceasefire protest in Capitol rotunda lead...,Capitol rotunda on Sept. 27. Photo: Michael Ro...,grievance,disruption,yes,no,yes,yes,disruption,disruption,yes,no,yes,no,4592,63,"{\n ""title_frame"": ""disruption"",\n ""excerpt_...",None
3,155faae5-c8b6-441e-a20e-dce06e01cf32,"Daniel Penny, accused in Jordan Neely subway c...",Neely and could not have foreseen his untimely...,residual,grievance,yes,yes,yes,no,residual,harm_to_protesters,yes,no,yes,no,4528,66,"{\n ""title_frame"": ""residual"",\n ""excerpt_fr...",None
4,50fea669-6828-44de-8a70-b448e398be11,Legal scholars raising constitutional argument...,Not all in the legal community agree – and wha...,residual,protester_violence,no,no,yes,yes,residual,grievance,yes,no,yes,yes,4845,64,"{\n ""title_frame"": ""residual"",\n ""excerpt_fr...",None

summary and results

In [7]:
# ============================================================
# EVALUATE MISTRAL AGAINST HUMAN GOLD
# ============================================================

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    precision_score,
    recall_score,
)

import simpledorff


# ------------------------------------------------------------
# KRIPPENDORFF ALPHA
# ------------------------------------------------------------

def calculate_alpha(y_true, y_pred):

    alpha_df = pd.DataFrame({
        "item_id": np.arange(len(y_true)).repeat(2),
        "annotator_id": ["human", "model"] * len(y_true),
        "label": np.column_stack([
            y_true.to_numpy(),
            y_pred.to_numpy()
        ]).reshape(-1)
    })

    return simpledorff.calculate_krippendorffs_alpha_for_df(
        alpha_df,
        experiment_col="item_id",
        annotator_col="annotator_id",
        class_col="label"
    )


# ------------------------------------------------------------
# TASKS
# ------------------------------------------------------------

tasks = {
    "title_frame": {
        "gold": "title_frame",
        "pred": "pred_title_frame",
        "type": "frame",
    },

    "excerpt_frame": {
        "gold": "excerpt_frame",
        "pred": "pred_excerpt_frame",
        "type": "frame",
    },

    "demands_present": {
        "gold": "demands_present",
        "pred": "pred_demands_present",
        "type": "binary",
    },

    "protester_quote": {
        "gold": "protester_quote",
        "pred": "pred_protester_quote",
        "type": "binary",
    },

    "authority_quote": {
        "gold": "authority_quote",
        "pred": "pred_authority_quote",
        "type": "binary",
    },

    "thematic_present": {
        "gold": "thematic_present",
        "pred": "pred_thematic_present",
        "type": "binary",
    },
}


# ------------------------------------------------------------
# METRICS
# ------------------------------------------------------------

summary_rows = []

for task_name, info in tasks.items():

    valid = results_df[
        [info["gold"], info["pred"]]
    ].dropna()

    y_true = valid[info["gold"]]
    y_pred = valid[info["pred"]]

    row = {
        "task": task_name,
        "n": len(valid),

        "accuracy": accuracy_score(
            y_true,
            y_pred
        ),

        "macro_f1": f1_score(
            y_true,
            y_pred,
            average="macro",
            zero_division=0
        ),

        "kripp_alpha": calculate_alpha(
            y_true,
            y_pred
        ),
    }


    if info["type"] == "frame":

        row["weighted_f1"] = f1_score(
            y_true,
            y_pred,
            average="weighted",
            zero_division=0
        )

        row["yes_precision"] = np.nan
        row["yes_recall"] = np.nan
        row["yes_f1"] = np.nan


    else:

        row["weighted_f1"] = np.nan

        row["yes_precision"] = precision_score(
            y_true,
            y_pred,
            pos_label="yes",
            zero_division=0
        )

        row["yes_recall"] = recall_score(
            y_true,
            y_pred,
            pos_label="yes",
            zero_division=0
        )

        row["yes_f1"] = f1_score(
            y_true,
            y_pred,
            pos_label="yes",
            zero_division=0
        )


    summary_rows.append(row)


summary_df = pd.DataFrame(summary_rows)

metric_cols = [
    "accuracy",
    "macro_f1",
    "yes_precision",
    "yes_recall",
    "yes_f1",
    "weighted_f1",
    "kripp_alpha",
]

summary_df[metric_cols] = (
    summary_df[metric_cols]
    .round(3)
)


display(summary_df)


# ------------------------------------------------------------
# SAVE SUMMARY
# ------------------------------------------------------------

summary_file = (
    f"summary_"
    f"{PROMPT_NAME}_{MODEL}.xlsx"
)

summary_df.to_excel(
    summary_file,
    index=False
)

print(f"Saved: {summary_file}")

,task,n,accuracy,macro_f1,kripp_alpha,weighted_f1,yes_precision,yes_recall,yes_f1
0,title_frame,120,0.700,0.570,0.492,0.725,NaN,NaN,NaN
1,excerpt_frame,120,0.508,0.439,0.392,0.478,NaN,NaN,NaN
2,demands_present,120,0.733,0.683,0.368,NaN,0.800,0.819,0.810
3,protester_quote,120,0.850,0.847,0.694,NaN,0.824,0.824,0.824
4,authority_quote,120,0.800,0.795,0.592,NaN,0.905,0.760,0.826
5,thematic_present,120,0.808,0.807,0.615,NaN,0.754,0.827,0.789

Saved: summary_operationalized_joint_mistral-large-latest.xlsx